### ISSUE TITLE
Дублирование кода 

### ISSUE THREAD

**Issue by maksgir** [rmntim/ITMO#1]
https://github.com/rmntim/ITMO/blob/7e32a3aa687a03bad5c2ad68479fe0906baddd0e/Programming/Labwork3/src/main/java/com/rmntim/models/people/Person.java#L73

ровно такой же метод есть в классе Communicator. надо что-то придумать чтоб дублирования не было.

**Comment by rmntim** [comment]
Сложная задачка получилась, но вот к чему я пришел. Есть 3 возможных варианта действий:
1. Добавить `default` к методу `dativeCase` в интерфейсе. Благодаря этому можно создать стандартную реализацию метода, что позволит избежать дублирования. Однако реализация `dativeCase` должна иметь доступ к условному `private String name`, но все поля в интерфейсках `public static final` by default, так что вариант не юзабельный.
2. Сделать `HasCase` абстрактным классом. В таком случае можно добавить условный `private String name`, но класс `Group` имени иметь не может, а метод `dativeCase` нужен. Тоже мимо.
3. Создать отдельный класс со статическим методом `toDative(String name)`. Вариант рабочий, плюс перегрузка методов позволит нам использовать данный метод с `Group`, однако это, на мой взгляд, говнокод и premature optimization. Я сделал отдельную [ветку](https://github.com/rmntim/ITMO/tree/bad-dative/Programming/Labwork3) для этого случая как демонстрацию, однако считаю, что в данном случае лучше просто оставить всё как есть ([поэтому](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself#WET) и [поэтому](https://kentcdodds.com/blog/aha-programming)).
