### ISSUE TITLE
Дубликат поля у наследника

### ISSUE THREAD

**Issue by maksgir** [rmntim/ITMO#2]
https://github.com/rmntim/ITMO/blob/7e32a3aa687a03bad5c2ad68479fe0906baddd0e/Programming/Labwork3/src/main/java/com/rmntim/models/actions/GoAction.java#L10

хранить два поля , еще и с одинаковым названием, у супер и наследника - такое. пусть будет единый destination у Action, а в наследниках задавайте его уже таким каким надо , типа super("отправляться " + dest).

**Comment by rmntim** [comment]
Fixed
